brp-desktop.data/xdg_menu

Regression in desktop category checking, errors can be seen in hardware:RC-Model/apm_planner factory build for example

- do not fail over new DefaultLayout element

---

brp-desktop.data/xdg_menu

This is the most common and most annoying error that cancels the build. The documentation at https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories is good, but hard to find as MediaWiki doesn't search the `openSUSE` namespace by default and all the names in the title are super generic so it can also be hard to google.

Added a link to the openSUSE packaging desktop menu categories

---

brp-desktop.data/xdg_menu

Fixes bb0a7d0 ("Hint to the desktop category rules. (#6)")
Signed-off-by: Olaf Hering <olaf@aepfle.de>

Add missing newline to Category error message

---

brp-25-symlink

Mounting a disk and inspecting "/etc/os-release" should give the information
of the mounted volume, not of the host drive.
https://bugzilla.opensuse.org/show_bug.cgi?id=1028408

brp-25-symlink: do not relink /etc/os-release

---

brp-75-ar

for normalizing ar archives (.a files) mtime, UID/GID
to facilitate bit-identical reproducible builds.
See https://reproducible-builds.org/ for why this is good.
This approach was suggested by matz in
https://build.opensuse.org/request/show/514997
and seems to work fine in my first tests

add brp-75-ar

---

brp-desktop.data/xdg_menu

Only hicolor is used as a generic fallback.
If Adwaita is mentioned here and explicitly allowed, all other common icon themes would need to be mentioned as well.

Don't treat Adwaita specially

---

brp-15-strip-debug

In order to not deliver a static library with a LTO bytecode, we should strip it.
Note that rpmlint can detect such ELF files. Having that, one can use `-ffat-lto-objects` option to both utilize LTO and deliver normal static libs as well.

Strip LTO bytecode from static libraries.

---

brp-75-ar

It would be useful for Go packages:
https://github.com/golang/go/issues/17890

Add NO_BRP_AR as a way how to skip ar.

---

brp-desktop.data/applications.menu

if you don't want to discard the whole test (#14), at least fix the categories according to the guidelines (https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories). Fixes the specific mentioned categories in #4 
Other categories than Science and Education possibly still need to be updated to the current guidelines.

redefine Science and Education to comply with guidelines

---

brp-desktop.data/applications.menu

Add the subcategories X-KDE-Edu-Teaching and Teaching (not in upstream spec yet) to the Education menu as specified in https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories.
Missing X-KDE-Edu-Teaching breaks some KDE packages according to a comment in #18 and #26

add Teaching and X-KDE-Teaching to Education

---

brp-15-strip-debug

otherwise it fails with message 
```
calling /usr/lib/rpm/brp-suse.d/brp-15-strip-debug
/usr/lib/rpm/brp-suse.d/brp-15-strip-debug: line 33: /dev/fd/62: No such file or directory
/usr/lib/rpm/brp-suse.d/brp-15-strip-debug: line 47: /dev/fd/62: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.1LutDl (%install)
```

refactor brp-15-strip-debug to not use /dev/fd/62

---

brp-15-strip-debug

Also strip lto data from `.o` files
to make build of our `pcc` package reproducible.
https://bugzilla.opensuse.org/show_bug.cgi?id=1146634

Also strip lto data from .o files (boo#1146634)

---

brp-25-symlink

update-alternatives expects (and writes) absolute symlinks, so relinking
those causes harm when updating the package. See https://bugzilla.opensuse.org/1172896

Make links *to* /etc/aternatives absolute links

---

prg-brp-symlink/Makefile
prg-brp-symlink/ghc/filesystem.hpp
prg-brp-symlink/main.cpp

Gcc 7 does not have c++17 (but kindly ignores the command line to enable it),
so we need a fallback header - newer compilers will still use the builtin
implementation.
The background is that we're using the Factory version of brp-check-suse
for carwos

Make prg-brp-symlink compile on SLE15

---

brp-25-symlink

Avoid using a subshell from a pipe - otherwise had_errors is always 0

Fix error handling of brp-25-symlink

---

prg-brp-symlink/main.cpp
prg-brp-symlink/tests.in
prg-brp-symlink/tests.out

Just skip . and do not add it to paths. It wouldn't work for pop_back
later.
Add a testcase for this too.
bsc#1179082

skip . in links

---

prg-brp-symlink/main.cpp

It should provide the very same result, but it simpler, and maybe
faster.

simplify split_paths using std::getline

---

prg-brp-symlink/Makefile

Use `CXXFLAGS` and `CXX` and enable `-O2`. `-I.` is no longer needed.
`-O2` improves the times by ~ 45 % here -- on 100 times of `tests.in` it
goes from 1800 to 1000 ms.

Makefile: enable `-O2` and use standard variables

---

brp-25-symlink

Previously, RPM took care of checking that, but it only does that for symlinks
with an absolute target path. This script blindly converts them to relative
paths though, so add a check here.
Also contains a commit to print all errors in one run, instead of exiting prematurely.

Detect if a link points inside the build root

---

brp-25-symlink

Avoid triggering on situations like:
mkdir /usr/lib/64/libsub
%install
cp libfoo.so.0 /usr/lib/64/libsub
ln -s libfoo.so.0 /usr/lib/64/libsub/libfoo.so
ln -s /usr/lib64/libsub /etc/alternatives/subdir
ln -s /etc/alternatives/subdir /usr/lib64/subdir
ln -s subdir/libfoo.so /usr/lib64/libfoo.so
%files
/usr/lib64/libfoo.so
by following links along the way.
Signed-off-by: Egbert Eich <eich@suse.com>

brp-25-symlink: Follow deeper symlinks to avoid false positives

---

brp-25-symlink

Full story at https://bugzilla.opensuse.org/show_bug.cgi?id=1186710

Let symlinks from /lib/modules to /usr/src be absolute

---

brp-25-symlink

783988906f1362e9a48e2bbbf41a880c97396ff3 had an unexpected side effect.
/etc/alternatives is not only mapped to be an absolute link, it's also
white listed for non-existant as it skips the case
So adding the white list back for it

Fix /etc/alternatives being white listed

---

prg-brp-symlink/main.cpp

See boo#1190528; the change to absolute symlinks breaks `find-provides.ksyms`.
Because the kernel is usrmerged now, the relative links will be correct again.
Reverts: 823d04c ("Let symlinks from /lib/modules to /usr/src be absolute")
~don't merge yet - testing in IBS (home:mwilck:usrmerge)~
Meanwhile I've tested this, and it actually fixes the issue.

Revert "Let symlinks from /lib/modules to /usr/src be absolute"

---

brp-50-generate-fips-hmac

this allows to move away from fipscheck, which is not openssl-3 compatible

fallback to the libkcapi fipscheck

---

brp-15-strip-debug

We do not want to have livepatchable sections on static libraries shipped in SLE, as it can be a source of problems (bsc#1208721).
As suggested by @marxin .

Remove __patchable_function_entries from .a objects
